# -*- coding: utf-8 -*-
"""2502.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oGDj_xJLOgYVlEMBhVdpKkAvFryX6t6j
"""

import pandas as pd
import statsmodels.formula.api as sms
import matplotlib.pyplot as plt
import numpy as np
# %matplotlib inline

# Lendo dados da web
adv = pd.DataFrame.from_csv("http://www-bcf.usc.edu/~gareth/ISL/Advertising.csv")
adv.head()

# Tirando estatisticas descritivas

adv.describe()

# Verificar as dimensçoes do banco

adv.shape

# A mesma coisa de um jeito mais metido a besta

r, c = adv.shape
print ("O banco de dados possui {} linhas e {} colunas".format(r,c))

# Verificando a distribuição da variavel respsta

plt.hist(x=adv['sales'])
plt.title("Histograma de Sales")
plt.ylabel("Frequencia")
plt.show()

# Verificar a distribuição da variavel TV com um histograma
plt.hist(x=adv['TV'], color="pink")
plt.title('Histograma de Investimento em TV')
plt.ylabel("Frequência")
plt.show

# Verificar a distribuição da variavel radio com um histograma
plt.hist(x=adv['radio'], color="#B03060")
plt.title('Histograma de Investimento em rádio')
plt.ylabel("Frequência")
plt.show

# Plotar o grafico identificandoa relação entre investimento em TV e retorno em vendas

plt.scatter(x=adv["TV"], y=adv["sales"], color="#B03060")
plt.ylabel("Sales")
plt.xlabel("Investimento em TV")
plt.show

# Montando um modelo de regressão

model = sms.ols(formula="sales ~ TV", data=adv).fit()

print(model.summary())